//go:build source && source_static && linux

package zvec

// Static source mode (Linux): use the zvec C-API static archive built from the
// git submodule. The full static linker line is intentionally supplied by
// scripts/build-static-smoke.sh through CGO_LDFLAGS because the transitive
// C++ archive set is generated by CMake and changes with zvec.
//
// Usage:
//   scripts/build-static-smoke.sh

/*
#cgo CFLAGS: -I${SRCDIR}/zvec/src/include -I${SRCDIR}/zvec/build/src/generated
*/
import "C"
